version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-food
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_db
      MYSQL_USER: food_user
      MYSQL_PASSWORD: food_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: