spring.application.name=food

spring.datasource.url=jdbc:mysql://localhost:3306/food_db
spring.datasource.username=food_user
spring.datasource.password=food_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

gemini.api-key = AIzaSyDUjGB_ZpFhJDBpAlUNAVfIvGSaOeHr1kY
gemini.model = gemini-2.5-flash